### ISSUE TITLE
[SUGGESTION] Add public lobbies discovery

### ISSUE THREAD

**Issue by ghost** [willuwontu/LobbyCodes#18]
Add public lobbies discovery
My idea is, that there will be button in online menu, for example "public lobbies" and when you click it, there is list of lobbies which are set to public by host, this will bring a lot of fun, because people will able to play with strangers.

**Comment by willuwontu** [comment]
Not possible due to the way lobbies are implemented in Vanilla Rounds, along with the fact that you need the same mods for modded lobbies.
